version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: always
    links:
      - db

volumes:
  db_data:
