version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3307

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./dynamic:/var/www/dynamic
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  nginx:
    image: nginx:1.27.2
    restart: always
    volumes:
      - ./static:/var/www/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web_server

